# Set base image
FROM node:current-buster-slim

# Copy backend folder
COPY backend/ /home/node/backend

#Change working dir
WORKDIR /home/node/backend/

# Install node packages
RUN npm install --dd

# Expose port to host
EXPOSE 5000

# Command
CMD /bin/bash -c "cd /home/node/backend/ && npm start"