# Set base image
FROM node:current-buster-slim

# Change user
USER node

# Copy backend folder
COPY backend/ /home/node/backend

# Install node packages
RUN npm install --dd

# Command
CMD /bin/bash -c "cd /home/node/backend/ && npm start"